# Generated by Django 5.1.1 on 2024-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_discount_product_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
