# Generated by Django 5.1.1 on 2024-09-23 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
