# Generated by Django 5.1.1 on 2024-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemnumber',
            field=models.TextField(default='itemnumber'),
        ),
    ]
