# Generated by Django 5.1.1 on 2024-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_itemnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemnumber',
            field=models.TextField(),
        ),
    ]
