# Generated by Django 5.1.1 on 2024-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_itemnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='your brand name', max_length=244),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemnumber',
            field=models.TextField(default='PMS-0001'),
        ),
    ]
