# Generated by Django 5.1 on 2024-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_product_remove_order_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='firstName',
            field=models.CharField(default='nothing', max_length=244),
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(default='nothing', max_length=244),
        ),
    ]
