# Generated by Django 5.1 on 2024-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_order_name_order_firstname_order_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='addressLine',
            field=models.CharField(default='nothing', max_length=244),
        ),
    ]
