# Generated by Django 5.1.1 on 2024-09-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_phone_alter_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
