# Generated by Django 5.1.1 on 2024-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemnumber',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
