# Generated by Django 5.1.1 on 2024-09-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_order_itemnumber_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
