# Generated by Django 5.1.1 on 2024-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_order_price_remove_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
