# Generated by Django 5.1.1 on 2024-10-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='crausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='crausel')),
            ],
        ),
    ]
