# Generated by Django 4.2 on 2024-10-10 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_crausel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='addressLine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line',
            field=models.CharField(default='your address', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='your first name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='item_numbers',
            field=models.JSONField(default='number'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='your last name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.JSONField(default='quantites'),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='your zip code', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='your city', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='your phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='your state', max_length=100),
        ),
    ]
