# Generated by Django 5.1.1 on 2024-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_total_order_total_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='modal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='modal1')),
            ],
        ),
    ]
