# Generated by Django 5.1.1 on 2024-10-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_modal1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_id',
            field=models.CharField(default='31352', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantities',
            field=models.JSONField(default=list),
        ),
    ]
