# Generated by Django 5.1.1 on 2024-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_order_created_at_remove_order_custom_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crauselsofdesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='crauselsofdesign')),
            ],
        ),
    ]
