# Generated by Django 5.1.1 on 2024-10-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_crauselsofdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Order Received'), ('on_the_way', 'On the Way'), ('shipped', 'Shipped')], default='received', max_length=20),
        ),
    ]
