# Generated by Django 5.1.1 on 2024-10-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
