# Generated by Django 5.1.1 on 2024-10-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_orderitem_total_alter_order_id_and_more'),
    ]

    operations = [
    ]
