# Generated by Django 4.1.13 on 2024-10-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemnumber',
            field=models.TextField(default='PMS-0001', unique=True),
        ),
    ]
